### ISSUE TITLE
Nextcloud 10 Compatibility

### ISSUE THREAD

**Issue by rrrnld** [dmsdevs/dms#2]
Are there any tests done to ensure nextcloud 10 compat? When trying to install it (via the web ui) I get the following log entries:

```
Error 	no app in context 	Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"deadmanswitch.page.index\" as such route does not exist.","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(333): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('deadmanswitch.p...', Array, 1)\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/CachingRouter.php(60): OC\\Route\\Router->generate('deadmanswitch.p...', Array, false)\n#2 \/var\/www\/html\/nextcloud\/lib\/private\/URLGenerator.php(69): OC\\Route\\CachingRouter->generate('deadmanswitch.p...', Array)\n#3 \/var\/www\/html\/nextcloud\/lib\/public\/Util.php(323): OC\\URLGenerator->linkToRoute('deadmanswitch.p...', Array)\n#4 \/var\/www\/html\/nextcloud\/apps\/deadmanswitch\/appinfo\/app.php(26): OCP\\Util::linkToRoute('deadmanswitch.p...')\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/NavigationManager.php(64): OC_App::OCA\\DeadManSwitch\\AppInfo\\{closure}()\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/app.php(714): OC\\NavigationManager->getAll()\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/TemplateLayout.php(83): OC_App::getNavigation()\n#8 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/template.php(228): OC\\TemplateLayout->__construct('user', 'files')\n#9 \/var\/www\/html\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(157): OC_Template->fetchPage()\n#10 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#11 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files\\Controller\\ViewController), 'index')\n#12 \/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ViewController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#13 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#15 \/var\/www\/html\/nextcloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/files')\n#16 \/var\/www\/html\/nextcloud\/index.php(48): OC::handleRequest()\n#17 {main}","File":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":130} 	2016-12-12T08:31:07+00:00
Error 	no app in context 	Exception: {"Exception":"Error","Message":"Class 'OCP\\Backgroundjob' not found","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/app.php(195): require_once()\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/app.php(153): OC_App::requireAppFile('deadmanswitch')\n#2 \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/app.php(123): OC_App::loadApp('deadmanswitch')\n#3 \/var\/www\/html\/nextcloud\/lib\/base.php(967): OC_App::loadApps()\n#4 \/var\/www\/html\/nextcloud\/index.php(48): OC::handleRequest()\n#5 {main}","File":"\/var\/www\/html\/nextcloud\/apps\/deadmanswitch\/appinfo\/app.php","Line":40} 	2016-12-12T08:31:07+00:00 
```

My setup is php 7 / nginx / mariadb.

**Comment by dmsdevs** [comment]
The routing issue has been solved and it generally works with nextcloud now (tested on nextcloud 11)
However the Backgroundjob still does not work. I am trying to fix this shortly.

If someone know what nextcloud changed regarding backgroundjobs, please let me know

**Comment by dmsdevs** [comment]
I may have solved the issue with the background task but I currently  do not have a (mail)server to test this reliably.

Please report if the app is working on nextcloud and mails are actually sent.

**Comment by brantje** [comment]
No need for a mail server, you can use [MailCatcher](https://mailcatcher.me/) for this.
I use it local in a docker container to confirm nextcloud is sending mails.
Btw, incorporating this app with passman would be nice. If you want to know what passman is, [link](https://github.com/nextcloud/passman).

**Comment by e-alfred** [comment]
Passman integration would be great.

Do you also intend to put your app into the Nextcloud store at https://apps.nextcloud.com?

**Comment by skyynet** [comment]
Doesn't work in Nextcloud and isn't available through the apps.nextcloud.com AppStore. Is Dead Man Switch dead now?

**Comment by e-alfred** [comment]
@skyynet Seems like Dead Man Switch is dead, sadly.
